# default values
all:
  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    default_image: { mime_type: image/png, filename: Untitled.png }
    font_dir: /usr/share/fonts/truetype/msttcorefonts
